# Generated by Django 5.2 on 2025-05-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Basicos', 'Básicos'), ('Fijacion', 'Fijación'), ('Manuales', 'Herramientas Manuales'), ('Seguridad', 'Equipos de Seguridad')], default='Basicos', max_length=20),
        ),
    ]
